					<!-- Dalaverka's slider -->
					<div class="dalav-slider">
						<div class="display">
							<div id="slide-1" class="slide current">
								<a href="#" class="banner-link">
									<img src="http://www.easypress.zqpalnik.com/wp-content/uploads/2019/09/new20-13-of-4.jpg" class="banner-image">
								</a>			
							</div>
							<div id="slide-2" class="slide">
								<a href="#" class="banner-link">
									<img src="http://www.easypress.zqpalnik.com/wp-content/uploads/2019/09/flatsomebilder-5-of-10.jpg" class="banner-image">
								</a>			
							</div>
							<div id="slide-3" class="slide">
								<a href="#" class="banner-link">
									<img src="http://www.easypress.zqpalnik.com/wp-content/uploads/2019/09/home-header-banner-2.jpg" class="banner-image">
								</a>			
							</div>
						</div>
						<div class="controls">
						    <div class="left-button">
						    	<button type="button" title="Предишен слайд"><i class="fas fa-chevron-left"></i></button>
						    </div>
						    <div class="right-button">
						    	<button type="button" title="Следващ слайд"><i class="fas fa-chevron-right"></i></button>
						    </div>
						</div>
						<div class="pagination">
							<ul>
								<li id="pag-slide-1" class="pag-slide current">
									<a role="button">
										<img src="http://www.easypress.zqpalnik.com/wp-content/uploads/2019/09/new20-13-of-4.jpg" class="thumbnail">
									</a>
								</li>
								<li id="pag-slide-2" class="pag-slide">
									<a role="button">
										<img src="http://www.easypress.zqpalnik.com/wp-content/uploads/2019/09/flatsomebilder-5-of-10.jpg" class="thumbnail">
									</a>
								</li>
								<li id="pag-slide-3" class="pag-slide">
									<a role="button">
										<img src="http://www.easypress.zqpalnik.com/wp-content/uploads/2019/09/home-header-banner-2.jpg" class="thumbnail">
									</a>
								</li>
							</ul>
						</div>
					</div>
					